version: '3.8'

services:
  liquor-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4300:8080"
    volumes:
      - ./logs:/app/logs # Montaje de volúmenes para los logs
    container_name: liquor-backend
    restart: on-failure
    environment:
      DB_URL: jdbc:mysql://host.docker.internal:3306/prueba
      DB_USERNAME: root
      DB_PASSWORD: '#Cr1s714n#'
